/*
 * The User API
 * API to manage teams, members and tokens
 *
 * The version of the OpenAPI document: 1.3.13 bordering-jerilyn
 * Contact: dev@lab5e.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lab5e.user.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for AnAPIToken
 */
public class AnAPITokenTest {
    private final AnAPIToken model = new AnAPIToken();

    /**
     * Model tests for AnAPIToken
     */
    @Test
    public void testAnAPIToken() {
        // TODO: test AnAPIToken
    }

    /**
     * Test the property 'resource'
     */
    @Test
    public void resourceTest() {
        // TODO: test resource
    }

    /**
     * Test the property 'write'
     */
    @Test
    public void writeTest() {
        // TODO: test write
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

    /**
     * Test the property 'lastUse'
     */
    @Test
    public void lastUseTest() {
        // TODO: test lastUse
    }

    /**
     * Test the property 'uses'
     */
    @Test
    public void usesTest() {
        // TODO: test uses
    }

}
