/*
 * The User API
 * API to manage teams, members and tokens
 *
 * The version of the OpenAPI document: 1.3.6 crooked-daija
 * Contact: dev@lab5e.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lab5e.user.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.lab5e.user.model.Invite;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for DeleteInviteResponse
 */
public class DeleteInviteResponseTest {
    private final DeleteInviteResponse model = new DeleteInviteResponse();

    /**
     * Model tests for DeleteInviteResponse
     */
    @Test
    public void testDeleteInviteResponse() {
        // TODO: test DeleteInviteResponse
    }

    /**
     * Test the property 'invite'
     */
    @Test
    public void inviteTest() {
        // TODO: test invite
    }

}
