/*
 * The User API
 * API to manage teams, members and tokens
 *
 * The version of the OpenAPI document: 1.3.4 breezy-leafy
 * Contact: dev@lab5e.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lab5e.user;

import com.lab5e.ApiException;
import com.lab5e.user.model.RpcStatus;
import com.lab5e.user.model.Token;
import com.lab5e.user.model.TokenList;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TokensApi
 */
@Ignore
public class TokensApiTest {

    private final TokensApi api = new TokensApi();

    
    /**
     * Create token
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void userCreateTokenTest() throws ApiException {
        Token body = null;
        Token response = api.userCreateToken(body);

        // TODO: test validations
    }
    
    /**
     * Remove token
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void userDeleteTokenTest() throws ApiException {
        String token = null;
        Object response = api.userDeleteToken(token);

        // TODO: test validations
    }
    
    /**
     * List tokens
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void userListTokensTest() throws ApiException {
        TokenList response = api.userListTokens();

        // TODO: test validations
    }
    
    /**
     * Retrieve token
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void userRetrieveTokenTest() throws ApiException {
        String token = null;
        Token response = api.userRetrieveToken(token);

        // TODO: test validations
    }
    
    /**
     * Update token
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void userUpdateTokenTest() throws ApiException {
        String token = null;
        Token body = null;
        Token response = api.userUpdateToken(token, body);

        // TODO: test validations
    }
    
}
